### ISSUE TITLE
Grouping function 

### ISSUE THREAD

**Issue by 8mk** [grafana/github-datasource#104]
Is there the possibility to create some grouping function like count, min, max...

The use case behind is for example the issues.

To display how many issues are open and closed during the day/week, or to identify the oldest issue, or the last one.

**Comment by kminehart** [comment]
I would rather wait on features like this for Grafana to implement them, since I believe efforts are being made for this kind of thing. It's a bit of a tall order.

**Comment by gabor** [comment]
i recommend using grafana transformations ( https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/ ) for this use-case. if anything is missing there, the list of transforms can always be extended with new ones.

if there's some functionality where you think transforms are not the way to go please reply and we can reopen the issue to discuss it.
