### ISSUE TITLE
Add Actions Data

### ISSUE THREAD

**Issue by RichiCoder1** [grafana/github-datasource#105]
There's a lot of good data we'd like to visualize from Actions:
* Overall Minutes Usage
* Per Workflow Success/Failure Counts and Runtime

**Comment by kminehart** [comment]
Interesting. I've not looked at the Actions API at all. I'll look into it soon.

**Comment by RichiCoder1** [comment]
It's a pretty recent addition but has a lot of good Actions-related data for billing and pipeline optimization. We're currently manually ingesting it into Prom.

**Comment by fhirt** [comment]
Hi there. I would be very interested in this feature. We would like to be able to monitor github-workflows on our organization repositories as well as the condition of our self-hosted runners. Is anybody already on this or shall I start on a pull request?

**Comment by Shahard2** [comment]
Interested as well.

When it will be available?

**Comment by SMR39** [comment]
bump

**Comment by mamatagelanee07** [comment]
would be interested in this too.

**Comment by dbg-raghulkrishna** [comment]
would be interested in this too.

**Comment by adziura-ledger** [comment]
Also interested

**Comment by Jyoti492** [comment]
interested ... any ETA ?

**Comment by zoltanbedi** [comment]
This is not currently in our roadmap but we are open for contributions!

**Comment by Jyoti492** [comment]
sure would love to work on this but this is the entire code we can modify and work ?? or do we need any database entry from behind ?

**Comment by zoltanbedi** [comment]
@Jyoti492 Please take a look at the https://github.com/grafana/github-datasource/blob/main/docs/developer-guide.md it should answer all your question if you still have any please reach out in our [public slack](https://slack.grafana.com/) channel.

**Comment by callppatel** [comment]
Any idea, when this will be available?

**Comment by rgarrigue** [comment]
Would also love an example dashboard to get started :)

**Comment by gkech** [comment]
Also interested

**Comment by gabor-grafana** [comment]
this should be coevered by https://github.com/grafana/github-datasource/pull/240 . 
if there's anything missing, please create a new github issue detailing what is missing. thanks!
