### ISSUE TITLE
"Query (optional)" field seems to be set as readonly in dashboard variables

### ISSUE THREAD

**Issue by eamonryan** [grafana/github-datasource#111]
Grafana: 7.4.3
Plugin version: 1.0.6
Browser: Firefox 85.0.1 for Ubuntu (actually elementaryOS)

**What's happening:** 
When tweaking dashboard variables, I notice that the error `Templating [varname] Error updating options: "query" is read-only` pops up quite a lot.

**Example:**
![image](https://user-images.githubusercontent.com/11842311/109866873-b0139780-7c1a-11eb-8b24-e96a4605c87a.png)

**What I expected to happen:** 
I expect to not get a bunch of errors when modifying dashboard variables

**What I think is causing it:** 
It seems like the field "Query (optional)" is the culprit. I'm guessing that the actual query sent to GitHub is generated by the other field selections and so even though it's been set as editable in the UI, it's not actually editable somewhere else in the plugin which throws the error anytime I try to modify it. Or indeed, on some dashboard loads if the variable is configured incorrectly.

**Comment by gabor** [comment]
hi @eamonryan , sorry for the late response, could you try this with the current grafana and plugin version? is this still happening?

if it still does, please give us more info about how we can reproduce this.

thanks!

**Comment by eamonryan** [comment]
On a quick glance I don't see this error thrown but it's been 3 years so hopefully some things changed in that time :)
