### ISSUE TITLE
add `label1 AND label2` style multi-select for labels

### ISSUE THREAD

**Issue by eamonryan** [grafana/github-datasource#113]
summary by @gabor : when using multiselect-dashboard-variables for labels, we combine them into an `a OR b` query. there currently is no way to do an `a AND b` query.

---

Grafana: 7.4.3
Plugin version: 1.0.6
Browser: Firefox 85.0.1 for Ubuntu (actually elementaryOS)

**What's happening:** 
I'm trying to use GitHub labels as a dashboard variable to filter on various things. Enabling multi-select of this dashboard variable is allowed, but when actually selecting >1 label for filtering, no results are returned. 

**What I expected to happen:** 
If I select multiple labels and my panel queries have `labels:$labels` as part of the query, I'd expect the query to return all results that feature all of the selected labels. For example, if I have issues with the labels `enhancement` and issues with the label `metrics` I'd expect selecting both labels would return results that have both labels.

**What I think is causing it:** 
My guess is there's currently no logic to translate Grafana's multi-select pattern into the relevant GitHub query. I think GitHub requires you to specify labels separately e.g. `label:enhancement label:metrics`.

**Comment by gabor** [comment]
hi @eamonryan , when you choose multiple labels (let's say you choose both `type/bug` and `type/feature-request` ), then the following filter is produced: `label:type/bug,type/feauture-request`. which causes an `OR` query, it filters out things that have either the `type/bug` label or the `type/feature-request` label.

now, i understand your use-case needs an `AND` nor an `OR`, but right now there's no support for this. i'll mark this as a feature-request.

**Comment by gabor** [comment]
hi @eamonryan , actually we do have support fort this. if you check here https://github.com/grafana/github-datasource?tab=readme-ov-file#macros , it describes the `$__multiVar` macro, and it will do what you need to do.

**Comment by eamonryan** [comment]
@gabor Yes, looks like it was added in #162 a year after I opened this issue :)
