### ISSUE TITLE
Strangely old timestamps returned in some results

### ISSUE THREAD

**Issue by eamonryan** [grafana/github-datasource#114]
Grafana: 7.4.3
Plugin version: 1.0.6
Browser: Firefox 85.0.1 for Ubuntu (actually elementaryOS)

**What's happening:** 
I'm using the default dashboard and looking at, for example, returned pull requests. I've noticed that some of the table columns have really old timestamps that are all the same exact timestamp from the 18th century. `1754-08-30 14:50:43` to be precise. Older than the Linux epoch, surprisingly.

This happened against multiple sample repositories, even `grafana/grafana`.

**Screenshot:**
![image](https://user-images.githubusercontent.com/11842311/109869201-6f694d80-7c1d-11eb-8d23-fd9edd68df26.png)

**What I expected to happen:** 
I would expect the `closed_at` and `merged_at` timestamps to be accurate.

**What I think is causing it:** 
My guess is there's some strange empty/null/absent value that's just being displayed as this by default.

**Comment by kminehart** [comment]
How do you know that these events aren't just that old? ;)

thanks for reporting this one. I know I've seen this in a couple different datasources.

**Comment by eamonryan** [comment]
On a possibly related note, on some repos, the same columns return a different timestamp but they are also all identical between themselves:

![image](https://user-images.githubusercontent.com/11842311/109869658-06cea080-7c1e-11eb-97cc-78e41a12e3ee.png)

These are different PRs and no they were not all closed and merged at the exact same instant :)

**Comment by santiagoesteva** [comment]
I see the same problem where all these columns are returning the same date

**Comment by kminehart** [comment]
yeah that's interesting. I wonder if that's related to some `for ... range` shenanigans. I'll take a look at this ASAP. There's quite a bit on my plate atm but this is next on my list.

**Comment by woodsaj** [comment]
I just had a quick look at this. To support null values, these timestamp fields use pointers.  The problem is that when looping through the list of items returned from Github, the code is falling for the classic error of assigning the address of a loop variable.  On each iteration the loop variable is re-used, resulting in the value for all items in the output being set to the value of the last item processed.

https://github.com/grafana/github-datasource/blob/master/pkg/github/issues.go#L44

Should be something like
```
	for _, v := range c {
		var closedAt *time.Time
		if !v.ClosedAt.Time.IsZero() {
		        t := v.ClosedAt.Time
			closedAt = &t
		}
```

**Comment by kminehart** [comment]
I figured it would be something related to a range / pointer problem. Good call

**Comment by woodsaj** [comment]
#123 fixes this problem for Issues, but i think the same problem exists for other entities as well.

eg.

https://github.com/grafana/github-datasource/blob/master/pkg/github/pull_requests.go#L99
https://github.com/grafana/github-datasource/blob/master/pkg/github/releases.go#L45

**Comment by kminehart** [comment]
Good call, i didn't even consider that. I added a new PR for those and I checked all of the different framer functions for any other weird uses of pointers.
