### ISSUE TITLE
Error reporting on dashboard variables can be unclear

### ISSUE THREAD

**Issue by eamonryan** [grafana/github-datasource#116]
Grafana: 7.4.3
Plugin version: 1.0.6
Browser: Firefox 85.0.1 for Ubuntu (actually elementaryOS)

**What's happening:** 
I noticed when tweaking dashboard variables that the errors thrown are often vague/unclear. Sadly don't have a screenshot at the moment but things like "Query (optional)" being readonly and `p has no value` (or similar) are not super helpful when trying to figure out the piece of my dashboard variable query that is incorrect.

**What I expected to happen:** 
If there is an issue with part of my dashboard variable query selections, I'd like the actual error to be clearer in helping me identify the problem piece.

**Comment by gabor** [comment]
hi @eamonryan , thank you for raising the issue. could you please provide specific examples that we can reproduce to improve the situation? thanks!

**Comment by eamonryan** [comment]
I haven't touched this datasource in some time so haven't encountered errors lately, it's possible the reporting has improved in 3 years so I'll close this for now :)
