### ISSUE TITLE
"Time field" field displays twice under Annotations, with different values

### ISSUE THREAD

**Issue by eamonryan** [grafana/github-datasource#117]
Grafana: 7.4.3
Plugin version: 1.0.6
Browser: Firefox 85.0.1 for Ubuntu (actually elementaryOS)

**What's happening:** 
I noticed when trying to test Annotations that each annotation seems to have the text written twice:

![image](https://user-images.githubusercontent.com/11842311/109871015-945ec000-7c1f-11eb-91bb-5b28b95f23b6.png)

This wasn't a mixup between Issue opening/close time selections, or ones that were closed on the same day they were opened.

**What I expected to happen:** 
Annotations should only display the name of the queried field (e.g. Issue title) once

**What I think is causing it:** 
I looked at the annotation configuration page and noticed the "TIme Field" actually displays twice, with different capitalisation:

![image](https://user-images.githubusercontent.com/11842311/109871233-d982f200-7c1f-11eb-9447-77dbf7073241.png)

The values within each are different too.

`Time Field:`
![image](https://user-images.githubusercontent.com/11842311/109871361-f9b2b100-7c1f-11eb-84b4-c8b392d9c897.png)

`Time field:`
![image](https://user-images.githubusercontent.com/11842311/109871434-0cc58100-7c20-11eb-9a50-2374713610a8.png)

So given both are there, it's grabbing the title twice, I think.

**Comment by kminehart** [comment]
I think what I'll end up doing with this is upgrading the minimum required version to 7.2+ and using Grafana's built-in annotation editor.

**Comment by cletter7** [comment]
Should be fixed with https://github.com/grafana/github-datasource/pull/196
