### ISSUE TITLE
Can this plugin display the 'repository' field in the response to the tags, releases, and other queries?

### ISSUE THREAD

**Issue by robotparty** [grafana/github-datasource#126]
Hiya, 
We would like your plugin for annotations on our service graphs to show when a release of a service was done and correlate that with any new errors that show up. 
In our case this would be done primarily with git tags. 

The issue we have now is: since this datasource does not include the 'repository' field as part of the 'tag' or 'release' query results, we can't distinguish one repository's tag from another except by the annotation color. 

According to Github's v4 API docs, this field IS available as part of the response data: 

- https://docs.github.com/en/graphql/reference/objects#tag
- https://docs.github.com/en/graphql/reference/objects#release
- https://docs.github.com/en/graphql/reference/objects#label
- (looks like you do include it in the PR response data)

We'd like to be able to pick 'repository' from this field list under the annotations config:
![image](https://user-images.githubusercontent.com/972938/114447464-4e363e00-9b87-11eb-8e0c-d71f813a5efc.png)

I think having this field available may make the 'outer join' transformation available also. 
Can you please include the 'repository' field in the responses wherever it is available? 

TYVM, this will help us do some cool things...

**Comment by kminehart** [comment]
certainly! it should be pretty straightforward, we just need to add the `Repository` field to the type(s) and in the dataframe.

**Comment by MasterSpecter** [comment]
It'd also be cool if we do a composite thing for annotation text, something like `$repository $tag`, that grabs data from the specified fields. That way you could see all the necessary info in the annotation tooltip. But I don't know how big an ask that is.

**Comment by kminehart** [comment]
There is a PR open currently to change the annotation editor to the one that ships with Grafana. https://github.com/grafana/github-datasource/pull/125

this would allow you to select what fields you want to display as annotation tags

**Comment by robotparty** [comment]
Great news and thx for the quick replies! Will keep our eyes peeled for the release.

**Comment by robotparty** [comment]
Hello @kminehart, is there any news on this request? 
Should I be looking somewhere else for update?

**Comment by kminehart** [comment]
This should have been released already, no? Have you tried the latest releaese?

https://github.com/grafana/github-datasource/releases/tag/v1.0.10

**Comment by robotparty** [comment]
I do see now in the changelog that the repository fields changes are included in v1.011. 
Thanks, this is going to be very useful indeed! 
We will be giving it a try in the next couple days.  Cheers!

**Comment by kminehart** [comment]
It's live on Grafana.com. I think there's an API issue with the changelog or something. The version (v1.0.11) shows up on the left.
