### ISSUE TITLE
signature has been modified

### ISSUE THREAD

**Issue by santiagoesteva** [grafana/github-datasource#132]
I have docker based grana image which was working fine till this week. 
Now I'm getting 

`lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"grafana-github-datasource\"'s signature has been modified]`

Is this something generated by a change in this module or is it related to Grafana?

**Comment by kminehart** [comment]
Out of curiosity, what version of the docker image, and what environment variables?

**Comment by santiagoesteva** [comment]
Dockerfile
`
FROM grafana/grafana

# Disable Login form or not
ENV GF_AUTH_DISABLE_LOGIN_FORM "true"
# Allow anonymous authentication or not
ENV GF_AUTH_ANONYMOUS_ENABLED "true"
# Role of anonymous user
ENV GF_AUTH_ANONYMOUS_ORG_ROLE "Admin"
# Install plugins here our in your own config file
ENV GF_INSTALL_PLUGINS="grafana-github-datasource"

# Add provisioning
ADD ./provisioning /etc/grafana/provisioning
# Add configuration file
ADD ./config/grafana.ini /etc/grafana/grafana.ini
# Add dashboard json files
ADD ./provisioning/dashboards /etc/grafana/dashboards
`

I've also tried  adding
`
ENV GF_ALLOW_LOADING_UNSIGNED_PLUGINS="grafana-github-datasource"

`

**Comment by kminehart** [comment]
ok. Pretty sure this is both related to the release we've done recently and the fact that grafana has been getting more strict about matching the signature with what's in the plugin's zip file. I'll try to get this fixed ASAP.

**Comment by kminehart** [comment]
Could you check your log file and see if it mentions what files were not found that were in the manifest?

**Comment by santiagoesteva** [comment]
Looking at the logs I can see a log entry for missing files.

"grafana    | t=2021-05-19T15:15:49+0000 lvl=warn msg="The following files were not included in the signature" logger=plugins plugin=grafana-github-datasource files=[gfx_github_linux_arm64]"

**Comment by kminehart** [comment]
ahh that must be why I didn't see the error. What OS / CPU architecture are you running on?

**Comment by santiagoesteva** [comment]
Im running in a MacBook, Catalina version 10.15.7, Docker version 20.10.5, build 55c4c88

**Comment by santiagoesteva** [comment]
@kminehart any advice or tips on how to solve this would be highly appreciated. thank you!

**Comment by santiagoesteva** [comment]
@kminehart Should I open a different issue for the missing files?

**Comment by kminehart** [comment]
No this is probably sufficient. I looked at the ARM release and everything looked fine but... being on a linux desktop i don't really have a way to test this... And we're in the middle of a release so getting someone to help me atm is a bit tough.

I'll keep looking at it if I have time. I don't think it's breaking because of anything you've done. I'll keep asking around.

**Comment by kminehart** [comment]
Apparently Mac OS might have purged the executable from the zip file?

Can you check the zip file that was downloaded and see if all of the files are there?

**Comment by kminehart** [comment]
Also, could you try running this in the running container (without the GF_INSTALL_PLUGINS environment variable)

```
grafana-cli --debug plugins install grafana-github-datasource
```

To get into the running container you need to run `docker exec -it {container_id} /bin/sh`

**Comment by cletter7** [comment]
Hi @santiagoesteva is the issue still occurring for you?

**Comment by sesteva** [comment]
Hi. Some time later , I had to jump on other things and I don't have such setup anymore. I would not know if this is still going on. 
From my side , please close the issue. Thank you for following up.
