### ISSUE TITLE
Tag queries do not return tag names

### ISSUE THREAD

**Issue by WileESpaghetti** [grafana/github-datasource#141]
plugin version: 1.0.11
grafana version: v8.1.1 (90c87a52f7)
GitHub Access Token scopes: all selected

Tag names do not appear to be returned when using the Tags query type.

Steps to reproduce:
1. create GitHub datasource
2.  create a new dashboard
3. add a new panel
4. set the panel type to table
5. configure the github datasource to run a Tags query against a repository that has tags

Expected results:
* the table should will show a list of tag information

Actual results:
* The table only contains the header row
![image](https://user-images.githubusercontent.com/2218608/132108881-99db446f-3657-40af-a524-29340bbe31bc.png)

**Comment by WileESpaghetti** [comment]
Still doesn't work in with plugin version 1.0.15 and grafana version 9.1.1

**Comment by cletter7** [comment]
For the record: this is strange, it returns tags for `grafana/grafana` but don't see any results for `grafana/github-datasource`.

**Comment by wkneewalden** [comment]
Observe same behavior with v1.0.15. 

https://community.grafana.com/t/github-plugin-issue-with-query-type-tags/73706

Has any later version of plugin resolved issue?

**Comment by nkatarmal** [comment]
Is there any fix for this issue? We are also experiencing this issue.

**Comment by wkneewalden** [comment]
> Observe same behavior with v1.0.15.
> 
> https://community.grafana.com/t/github-plugin-issue-with-query-type-tags/73706
> 
> Has any later version of plugin resolved issue?

Same result with GitHub plugin v1.5.2 and using Grafana v10.1.1.
