### ISSUE TITLE
Datasource.yaml IaC definition of Grafana github datasource

### ISSUE THREAD

**Issue by michalzegar** [grafana/github-datasource#154]
Hello Everyone,

I like your plugin and via manual import and setup - works perfect. 
How about IaC ? I would like to setup datasources in YAML files similar to:

![image](https://user-images.githubusercontent.com/72020603/148035780-0583b2e6-e641-41f6-9c07-8e9619165061.png)

Access Token is necessary to proper define of github-grafana datasource.
Can you provide any example config, please ?

**Comment by tchellomello** [comment]
@michalzegar  From this code https://github.com/grafana/github-datasource/blob/main/cypress/integration/smoke.spec.ts#L86-L88

it seems you should use 

```yaml
jsonData:
  accessToken: xxxx
``` 

I tried and I see the datasource created but I had some issues to use it. Does it work for you?

**Comment by tchellomello** [comment]
Interestingly after I activated the plugin via UI, new deployments came back with it working. Maybe something gets stored in the database and therefore it is able to work.

**Comment by michalzegar** [comment]
This is working !!! Thanks a lot ;)
