### ISSUE TITLE
Most query types are not working with dashboard variabels

### ISSUE THREAD

**Issue by davinc** [grafana/github-datasource#166]
After importing the [default dashboard for GitHub](https://grafana.com/grafana/dashboards/14000), out of the box it returns error on most the panels as show below. The message `Could not resolve to a Repository with the name '$organization/$repository'.` appears for commits, contributors, milestones, packages.. it works for releases and tags.

Adding the owner and repository manually in the panel query edit screen works fine. It seems that the variables are not working correctly with the panels query for certain query types.

![Screen Shot 2022-05-02 at 5 45 23 PM](https://user-images.githubusercontent.com/843630/166232201-6f5028d2-2363-4e4d-bfcf-e175132524f9.png)

Environment: Docker Community Edition, v8.5.1 (61fe4a1859)

**Comment by andoriyu** [comment]
Can confirm. Regression in 1.0.14, works as expected in 1.0.13.
