### ISSUE TITLE
Open PR count doesn't show the open pull requests

### ISSUE THREAD

**Issue by revitteth** [grafana/github-datasource#168]
I have the datasource installed in grafana cloud, and when I try to use open_pull_request_count, they are all zero (despite PRs being open). However, if I use open_issue_count, this also reflects the open pull requests. 

This seems confusing, and doesn't allow for a clear view of PRs vs issues.

Thanks!

**Comment by cletter7** [comment]
Hi @revitteth, could you share if the issue still persists? If so, could you share the exact query you use?

**Comment by revitteth** [comment]
Unsure if it persists but probably some missing filter.

**Comment by cletter7** [comment]
@revitteth Could you share the query you are using so that I can try to reproduce the issue?

**Comment by gabor** [comment]
as we got no response in the long time, we are closing the issue. we will reopen it if we get the needed information.
