### ISSUE TITLE
Include state enum for Vulnerability Alerts

### ISSUE THREAD

**Issue by psof** [grafana/github-datasource#210]
The `RepositoryVulnerabilityAlertState` status allows the identification of current status (`DISMISSED|FIXED|OPEN`) for a Vulnerability alert. At the moment this is not included in the data source's data model which is crippling the ability to identify, for example, the currently open dependabot vulnerability alerts.

The information is accessible via the GraphQL API: 
https://docs.github.com/en/graphql/reference/enums#repositoryvulnerabilityalertstate

**Comment by baldm0mma** [comment]
great!
