### ISSUE TITLE
Monitoring GitHub workflow via Grafana

### ISSUE THREAD

**Issue by Jyoti492** [grafana/github-datasource#214]
I want to monitor GitHub with Grafana and I came across https://github.com/grafana/github-datasource which can do the trick.
Have added the data source as `cm` and added it as plugin in grafana deployment but my deployment fails saying it can't find the plugin
```
lvl=warn msg="invalid access value, will use 'proxy' instead" value=server
```

My configmap looks as below:

```
apiVersion: v1
data:
  github.yaml: |-
    apiVersion: v1
    datasources:
      - access: proxy
        name: GitHub
        type: grafana-github-datasource
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-01T21:26:19Z"
  name: github-datasource
  namespace: kube-prometheus-stack
  resourceVersion: "176513298"
  uid: 22d3a597-119f-48f9-970d-605bc258f135
```

tried this too but same issue:
```
apiVersion: v1
data:
  github.yaml: |
    apiVersion: v1
    datasources:
      - access: direct
        name: GitHub
        type: grafana-github-datasource
        url: https://api.github.com/
        jsonData:
          token: XXX
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-02T06:57:53Z"
  name: grafana-github-datasource
  namespace: kube-prometheus-stack
  resourceVersion: "296320328"
  uid: d3ce0d89-81a7-40d7-934d-2f896f925a9e
```

Expected:
Monitor Github workflow with grafana

**Comment by zoltanbedi** [comment]
I know nothing about kubernetes and configmaps so I'm not sure that what you are trying makes sense or not. I advise to read our provisioning guide and try to use that instead. https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources

Also if you are still stuck you may have better luck asking questions in the forum https://community.grafana.com/?plcmt=learn-nav
