### ISSUE TITLE
Cannot view private repos

### ISSUE THREAD

**Issue by leonid-deriv** [grafana/github-datasource#241]
I have configured data source as described in the docs and successfully got data from public repos. No data is returned from private organisations.  The token has repo permission.  Do I need to be owner of the organisation to view private repos.

**Comment by PoorlyDefinedBehaviour** [comment]
I can view private repos using a token from the `Tokens (Classic`) page with these permissions:

<img width="802" alt="Screenshot 2023-08-02 at 10 32 33" src="https://github.com/grafana/github-datasource/assets/17282221/1e103ba6-8f55-4c1f-9b4e-c356fef75019">

**Comment by leonid-deriv** [comment]
Thank you. I can view them now. The problem was that after token creation I had to configure SSO and I have not done it.
