### ISSUE TITLE
Issues Average Open Time (Closed issues) Default Panel - Not working

### ISSUE THREAD

**Issue by gjfvieira** [grafana/github-datasource#245]
Hi guys, 

I was wondering if you're facing the same issue, I cannot get the stats for the average open time for the closed issues using the dashboard provided here.

![image](https://github.com/grafana/github-datasource/assets/47488771/1c4a2847-8931-4a22-992b-ee356e7fe434)

Is there some workaround for this ?

Thank and kind regards,

**Comment by SgtPooki** [comment]
this is working for me with the default dashboard provided at https://github.com/grafana/github-datasource/blob/main/src/dashboards/dashboard.json

**Comment by gabor** [comment]
hi @gjfvieira, it is working for me correctly. 

 could you please try with the current grafana version and the current github-plugin-version? (make sure to delete the dashboard, and import from the current plugin version).

thanks!

**Comment by gabor** [comment]
as we received no feedback, we will close the issue. we can reopen it when we receive the needed info. thanks!
