### ISSUE TITLE
Checkboxes are not supported in grafana

### ISSUE THREAD

**Issue by gwdawson** [grafana/github-datasource#264]
in the README we use: `- [x] <feature-name>`,
these are not supported in grafana resulting in: `<input checked="" disabled="" type="checkbox"> <feature-name>`

<div>
<img width="49%" alt="Screenshot 2023-10-20 at 12 48 45" src="https://github.com/grafana/github-datasource/assets/34524710/8d5a865b-e32c-47aa-b5e4-3b28ae79f79a">
<img width="49%" alt="Screenshot 2023-10-20 at 12 50 31" src="https://github.com/grafana/github-datasource/assets/34524710/ee0d6f61-18d8-4619-833d-1c8642ac83f0">
</div>

**Comment by zoltanbedi** [comment]
Related to https://github.com/grafana/grafana-com/issues/7543

**Comment by zoltanbedi** [comment]
This got fixed!
