### ISSUE TITLE
Docker registry for GitHub Packages is replaced with Container registry

### ISSUE THREAD

**Issue by naing2victor** [grafana/github-datasource#285]
Github packages is replacing docker registry with container registry. Please refer here https://arc.net/l/quote/ataxrdtt.

Current plugin doesn't have `container` as package type under the dropdown. Hence query with the `packageType = Docker` value would return invalid value error and dropdown menu automatically changes back to `NPM`. 
![image](https://github.com/grafana/github-datasource/assets/45144897/3c76333d-57bd-4c08-b34a-313e3a1954d1)

**Comment by zoltanbedi** [comment]
Hey @naing2victor,

Thanks for letting us know I was able to reproduce this bug. It seems like that it is not what you say but for some reason the query sent without packageType in some scenario. Selecting DOCKER from the dropdown again should solve the issue.

**Comment by ivanahuckova** [comment]
Fixed in the newest version.
