### ISSUE TITLE
feature request: interested organizations

### ISSUE THREAD

**Issue by SgtPooki** [grafana/github-datasource#299]
instead of requiring users to manually type in organizations, how would we set up a list of organizations a team is interested in monitoring (libp2p, ipfs, and some others for my team) using a dashboard like https://github.com/grafana/github-datasource/blob/main/src/dashboards/dashboard.json?

In order to get some organization stats (avg PR open time for an organization as a whole, new open issues in a whole organization, total contributors across an organization) I had to manually set organization in a set of graphs.

I'm no grafana expert, so maybe there's an easy solution here, but how would one define a list of organizations and then repeat visualizations for all of those organizations?

Example of what i'm looking for:

![image](https://github.com/grafana/github-datasource/assets/1173416/f8ccdf8b-3d10-47bd-aabb-238e79639695)

but also "contributors" if possible.

this would also be useful for the grafana organization to see overall health

**Comment by gwdawson** [comment]
hey, if i understood this correctly you can do this using dashboard variables. i recorded a quick demo of how i would achieve this.

> NOTE: i'm going to close this issue, however if this didn't answer your question feel free to re-open

https://github.com/grafana/github-datasource/assets/34524710/fca230b9-10e5-4510-bd2a-10f99d9294fc

**Comment by SgtPooki** [comment]
@gwdawson I thought it should be easy with the repeat option. thanks for the super helpful demo
