### ISSUE TITLE
Documentation help

### ISSUE THREAD

**Issue by mightywomble** [grafana/github-datasource#314]
I'm trying to use this plugin to display the Github Actions workflows, I've got as far as figuring out how to create a basic dashboard 

![Screenshot 2024-06-05 14 29 18](https://github.com/grafana/github-datasource/assets/21082180/f0435ab8-c9ee-4044-8ed9-c593ebfd7b30)

I can't find any examples of working with Dashboard usage and looking for some pointers

I'd like to get a dashboard which displays for each repo/github action 

- Total Number of times the Workflow has Run 
- last run state (Run, failed, cancelled)
- graph of the run time of each consecutive workflow run
- The Days the action was run, and the status the last time it was run, so mon = ok, tue = ok, wed = failed, thur = ok fri = ok

I can see in places like annotations this data exists in fields, I just can't see how to write a query which does the above, I just get drop down menus.. any help or pointers would be well recieved

**Comment by gabor** [comment]
hi, thank you for submitting the issue. unfortunately, the github-issues are not really the place for usage questions, for those i recommend going to the grafana community forums: https://community.grafana.com/

thanks!
