### ISSUE TITLE
rxjs upgrade & migrate from `toPromise()`

### ISSUE THREAD

**Issue by kminehart** [grafana/github-datasource#33]
rxjs has deprecated `toPromise()` and we use it in 2 or 3 different places in `datasource.ts`

**Comment by ryantxu** [comment]
I'm not sure this is a real issue...  the places that use `toPromise` are matching the required promise API from the datasource

**Comment by kminehart** [comment]
When I tried upgrading rxjs it gave me deprecation warnings about toPromise.

https://indepth.dev/rxjs-heads-up-topromise-is-being-deprecated/

**Comment by ryantxu** [comment]
> When I tried upgrading rxjs

But note that a plugin can not upgrade rxjs -- rxjs is loaded from the runtime grafana *regardless* of which version you compile against!

**Comment by kminehart** [comment]
ahhh. that makes sense! I'll close this then. :) thanks for clarifying.
