### ISSUE TITLE
Update the github-datasource repository 'About' section

### ISSUE THREAD

**Issue by usmangt** [grafana/github-datasource#342]
Now we finally have the official documentation released after the PR https://github.com/grafana/github-datasource/pull/292. Please update this repository page to provide more detail 

**Description:**
(Current) Grafana data source plugin using the Github API to retrieve and visualize Github data.
(New suggestion) The GitHub data source lets you visualize GitHub data in Grafana dashboards

IF we would agree to keep the (Current) then just fix the minor typo from Github to GitHub

**Website:**
https://grafana.com/docs/plugins/grafana-github-datasource/latest/

**Topics:**

grafana, grafana-plugin, github-datasource, grafana-plugins, grafana-datasource

**Comment by usmangt** [comment]
cc @gabor

**Comment by gwdawson** [comment]
content updated
