### ISSUE TITLE
Adding link to the documentation in the plugin catalog page

### ISSUE THREAD

**Issue by usmangt** [grafana/github-datasource#343]
After search OR installing the plugin inside the web UI, it does not show a link to the documentation.

![image](https://github.com/user-attachments/assets/4446ef12-8c9c-4af6-926c-3b5657769240)

It will be good to have a link to the official documentation (reference e.g. the infinity plugin):

![image](https://github.com/user-attachments/assets/3d88234e-a111-4476-b574-0b0949cb0f78)

This will help the users to understand and use it correctly and also help us to make the docs better for any suggestions or future improvements.

**Comment by usmangt** [comment]
cc: @ivanahuckova

**Comment by ivanahuckova** [comment]
Hi @usmangt! I checked and it seems that infinity specifies it in its plugin json: https://github.com/grafana/grafana-infinity-datasource/blob/main/src/plugin.json. Feel free to add it to github plugin json: https://github.com/grafana/github-datasource/blob/main/src/plugin.json 🙂

**Comment by ivanahuckova** [comment]
Also it looks like it is using https://github.com/grafana/github-datasource/blob/main/README.md for overview. I am wondering, if we should change its content to what you created in https://github.com/grafana/github-datasource/blob/main/docs/sources/_index.md

**Comment by usmangt** [comment]
Thanks for the hint @ivanahuckova . I updated the plugin.json and here is the PR:
https://github.com/grafana/github-datasource/pull/344

**Comment by usmangt** [comment]
> Also it looks like it is using https://github.com/grafana/github-datasource/blob/main/README.md for overview. I am wondering, if we should change its content to what you created in https://github.com/grafana/github-datasource/blob/main/docs/sources/_index.md

Good point. Yes, that will be helpful for users.

How about if we simply put a new link in the current readme.md file "Link to the Documentation" and that way we do not need to change that much?

**Comment by ivanahuckova** [comment]
Yes, I think that is a good idea!

**Comment by usmangt** [comment]
> Yes, I think that is a good idea! Having a single source of truth so we don't have to update data source docs when something changes at 2 places.

Created this PR
https://github.com/grafana/github-datasource/pull/346

**Comment by usmangt** [comment]
Thank you @ivanahuckova for finishing both PR.

I will now close this issue !!
