### ISSUE TITLE
Add App Authentication to GitHub Data Source

### ISSUE THREAD

**Issue by gwdawson** [grafana/github-datasource#365]
improve the github data source by adding support for authentication using github apps. this will enable users to authenticate via github app private keys, improving security and aligning with best practices.

this feature has been highly requested by the community and has also been discussed internally as a priority.

**Comment by connorhsm** [comment]
Possible duplicate of https://github.com/grafana/github-datasource/issues/88

Would very much love this feature!

**Comment by gwdawson** [comment]
@connorhsm GitHub App authentication has been implemented as part of the [1.9.0](https://github.com/grafana/github-datasource/releases/tag/v1.9.0) release! You can check out the setup instructions and more details in the [documentation here](https://grafana.com/docs/plugins/grafana-github-datasource/latest/setup/token/#using-github-app-authentication).

Thanks for your patience, and feel free to reach out if you have any questions!
