### ISSUE TITLE
Caching not enabled by default?

### ISSUE THREAD

**Issue by karl-johan-grahn** [grafana/github-datasource#384]
I'm just curious, I though caching would be enabled by default but when I installed the datasource in Grafana Cloud, it is not enabled:
![Image](https://github.com/user-attachments/assets/a52f66f6-ce05-44eb-a85c-237ce43f3ebe)

I added it via Terraform:

```tcl
resource "grafana_data_source" "github_ds" {
  type = "grafana-github-datasource"
  name = "Grafana GitHub data source"
}

resource "grafana_data_source_config" "github_ds_config" {
  uid = grafana_data_source.github_ds.uid

  secure_json_data_encoded = jsonencode({
    accessToken = var.GRAFANA_GITHUB_DS_TOKEN
  })
}
```

So I have to configure to enable it, because it does not seem to be enabled by default?

**Comment by zoltanbedi** [comment]
It is not enabled by default. The datasource itself has caching built in, what you are seeing is caching in grafana cloud.

**Comment by karl-johan-grahn** [comment]
Can you clarify what the difference is between caching in the datasource itself and caching of the datasource in grafana cloud?
