### ISSUE TITLE
Support repeating repository by variable

### ISSUE THREAD

**Issue by maximbaz** [grafana/github-datasource#50]
Hi there!

I would like to have a simple table showing open PRs in all repos of my team within the organization.

At first I was hoping I could just specify a matching rule for repo name (all our repos start with `myteam-*` prefix), either specifying `myteam-*` as a repo name, or leaving repo name blank and using something like `myteam in:name`. 

That didn't seem to work, so I tried using "Repeat" as an alternative, I would create a dashboard variable `repo` with values `repo1,repo2`, use `$repo` in the query and set the table to repeat on `repo` variable. This _almost_ seems to work, if I look into "Query inspector" I can see that in the request `repository: "{repo1,repo2}"`, and I think that curly brackets are perhaps to blame here.

What do you think, could this be supported, or am I missing something?

**Comment by kminehart** [comment]
Hi Maxim, thanks for submitting our first issue!

I'll see what I can do. Both of your attempted solutions should be possible. :thinking:

**Comment by kminehart** [comment]
Here's what I think I'll do.

1. I'll add a way to list repositories for variables
2. I'll see if there's a way to search multiple repositories using the Pull Request search endpoint. This one may not be possible but #1 will help you accomplish the variable solution.
3. The repeat solution should work fine so I'll make sure everything is working properly there.

**Comment by maximbaz** [comment]
That was fast! Thank you, I'll give it a try!

**Comment by kminehart** [comment]
No problem!

I'm going to create a new release some time today that has this change in it. If you have any other issues don't hesitate to submit them.

**Comment by maximbaz** [comment]
Will do! 

I have just another very minor suggestion, when I tried the build my table for open PRs, at first I didn't enter anything in the "Time field" field and apparently it defaulted to "Closed timestamp" for pull requests, it took me quite some time to figure out what I am doing wrong, why I only see some pull requests and not all of them - after I explicitly set the "Time field" to  "Created timestamp", everything was good 🙂

**Comment by kminehart** [comment]
ah good call. Go sees nothing and assumes that it's the default value for an int (which is 0, or ClosedAt). We should definitely display it for pull requests.

I'll do that now and make that part of the release.

**Comment by kminehart** [comment]
@maximbaz You may find this interesting based on your description. You can now list all pull requests outside of your time range for an at-a-glance view of how many pull requests are open.

![image](https://user-images.githubusercontent.com/5140827/92964981-9e56f180-f43a-11ea-8913-688503ba56fb.png)

which matches the number of open PRs in github.com/grafana/grafana
