### ISSUE TITLE
Add PR ID, URL, and Repository to Pull Requests results

### ISSUE THREAD

**Issue by maximbaz** [grafana/github-datasource#60]
When querying pull requests, I would like to present them in a table and use "data link" to make the PR title a link that on click opens the PR on Github in a new browser tab. In general adding `url` property would probably be easiest to use, but if you could at least expose the PR `id` then I would be able to re-construct the full URL myself 🙂 

Let me know if this makes sense 🙂

**Comment by kminehart** [comment]
Easy enough. I'll add both!

**Comment by maximbaz** [comment]
Could you please also add repo name? I want to try merge transformation (where I would hardcode repo names directly in the queries - could later generate the dashboard JSON), and the only thing I would be missing in the merged table is the repo name next to the PR title. Thanks!

**Comment by kminehart** [comment]
Thanks for your feedback! It is much appreciated.

Just released v1.0.4, take a look when you have a chance.

**Comment by maximbaz** [comment]
Thanks for your help!

This might be a stupid question, but I don't see the new columns, I double-checked that the datasource version is `1.0.4`, but if I just create a brand new dashboard, new table panel, and in query I set "Github stats > Pull_Requests > fill owner > fill repo name > query empty > Time Field None", then I get some lines in the table, but they do not contain the new fields, it's just "title", "state", "author_login" and so forth...

Can you think of what I might be doing wrong?

**Comment by kminehart** [comment]
Ohh. I think I know what happened. I'm still getting used to the release process and I think I forgot to include my changes. Give me one minute.

**Comment by kminehart** [comment]
#70
