### ISSUE TITLE
Query type dropdown label is "Pull_Requests" and not "Pull Request"

### ISSUE THREAD

**Issue by kminehart** [grafana/github-datasource#65]
We probably have the regex replace flipped.

**Comment by vschettino** [comment]
Hey @kminehart could I give a shot on this one?

**Comment by kminehart** [comment]
of course! Anyone can!

My best guess is it's this line: https://github.com/grafana/github-datasource/blob/master/src/views/QueryEditor.tsx#L78

**Comment by vschettino** [comment]
Yep, exactly there! I wish I would've seen your (precise) best guess before searching it up :smile:
