### ISSUE TITLE
Update README about support for template variables

### ISSUE THREAD

**Issue by vschettino** [grafana/github-datasource#68]
As the README says:

> We have aggressive caching enabled due to GitHub's rate limiting policies. When selecting a time range like "Last hour", a combination of the queries for each panel and the time range is cached temporarily.
>
> - I am trying to use a template variable in the "Query" field and it's not working
>
>Template variables are currently not supported outside of the "Owner / Organization" and "Repository" fields.

I see it's done (#14, #29), but I feel like the FAQ on the README is outdated. I just tested and it works fine having a "milestone" variable addressed on Query field, as the prints show:

![Captura de tela de 2020-09-15 14-11-58](https://user-images.githubusercontent.com/7289698/93242614-77136380-f75d-11ea-8906-842108ff1ed8.png)
 
![Captura de tela de 2020-09-15 14-10-38](https://user-images.githubusercontent.com/7289698/93242791-b641b480-f75d-11ea-9e93-4580c8d6f654.png)

![Captura de tela de 2020-09-15 14-01-00](https://user-images.githubusercontent.com/7289698/93242723-9f02c700-f75d-11ea-96c3-b30d0b2ccdfa.png)

If you guys think this is a good idea, I can open a PR. We could just remove this FAQ item and add extra info about the support in the "variables" section.

**Comment by kminehart** [comment]
Yeah good call. This was fixed in this PR: https://github.com/grafana/github-datasource/pull/42
