### ISSUE TITLE
Support querying multiple repos at a time via query variables

### ISSUE THREAD

**Issue by jsheffield-roblox** [grafana/github-datasource#90]
## Problem
I would like to get metrics on multiple repos at a time. Technically, this is possible at the moment, just not with query variables.

I.E. Given the repos:
- `Org/repo_a`
- `Org/repo_a`

I can put the following in the query box `repo:Org/repo_a repo:Org/repo_b` 
<img width="1652" alt="Screen Shot 2020-10-21 at 12 06 06 PM" src="https://user-images.githubusercontent.com/70403061/96770896-d0daff00-1395-11eb-9b77-20fd2347700b.png">

This works. However, the issue becomes when trying to use query variables to accomplish this. 
<img width="1137" alt="Screen Shot 2020-10-21 at 12 06 58 PM" src="https://user-images.githubusercontent.com/70403061/96770979-f10abe00-1395-11eb-9c57-923b1413f38c.png">

Using this variable like so:
<img width="1679" alt="Screen Shot 2020-10-21 at 12 07 51 PM" src="https://user-images.githubusercontent.com/70403061/96771086-10095000-1396-11eb-8fa3-8b2ca90ffd48.png">

Just results in the query string being `repo:{Org/repo_a,Org/repo_b}`

I was unable to find any way to transform this string into what I need using the builtin grafana interpolation, as it seems to only support either plugin defined formats or a list of predefined formats [here](https://grafana.com/docs/grafana/latest/variables/formatting-multi-value-variables/)

## Proposed solution 
I believe this could be accomplished by simply splitting on commas in the `repository` field, then separating each of those into their own `repo:x` field in the query [here](https://github.com/grafana/github-datasource/blob/ec6dc858ce1cc4878b62603e2eff7582bfcbdf4f/pkg/github/pull_requests.go#L197), but I'm not sure if this is the best/desired way of accomplishing this.

So the final result would look something like this
<img width="1671" alt="Screen Shot 2020-10-21 at 12 27 08 PM" src="https://user-images.githubusercontent.com/70403061/96772975-c110ea00-1398-11eb-942a-42897b71d816.png">

where `$repo_name` is: `Org/repo_a,Org/repo_b` etc, then the generated query is `repo:Org/repo_a repo:Org/repo_b`

I'd be happy to create a pr to this effect, just want to make sure this is the "grafana" way of doing things and I'm not missing a better solution here!

**Comment by kminehart** [comment]
This is probably related to this:

https://github.com/grafana/github-datasource/issues/43

Basically we have to refactor the `replaceVariables` function to support these kinds of operations.

https://github.com/grafana/github-datasource/blob/master/src/DataSource.ts#L29

There are some default formatting options you can try, though I am not sure that they will work. 
https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/

Maybe try the CSV option? `${variable:csv}`

**Comment by jsheffield-roblox** [comment]
Hm, I'm not sure I'm communicating the problem correctly (or perhaps I just don't understand what you're saying!)

Basically, the variable replacement _does_ work, it just doesn't substitute it as anything meaningful _for repos_. 

Github's api seems to only support `repo:org/repo_a repo:org/repo_b repo:org/repo_c` as syntax for including multiple repos. The plugin currently only offers the ability to do `repo:org/repo_a,org/repo_b,org/repo_c` (this is the csv format method).

My suggestion is splitting on the csv's commas in the code go code [here](https://github.com/grafana/github-datasource/blob/ec6dc858ce1cc4878b62603e2eff7582bfcbdf4f/pkg/github/pull_requests.go#L197), and turning those comma separated values into the format that github expects,  `repo:org/repo_a repo:org/repo_b repo:org/repo_c`

**Comment by jsheffield-roblox** [comment]
@kminehart would you be willing to accept a pr to this effect? For the metrics we plan on collating with this plugin, we need support for multiple repos.

**Comment by kminehart** [comment]
Absolutely!

Sorry I haven't quite gotten to a lot of the issues on here yet. This plugin is part of our work on the Enterprise Plugins team and we support a lot of datasources. :D

**Comment by marcoaaguiar** [comment]
@jsheffield-roblox did you ever manage to make any implementation to solve this issue?
