### ISSUE TITLE
Querying for tags when creating an annotation

### ISSUE THREAD

**Issue by nazzzzz** [grafana/github-datasource#95]
I see that it's possible for the query type to be 'Tags` when creating a variable using this datasource, but not when creating an annotation. As far as I can tell, this limit is set [here](https://github.com/grafana/github-datasource/blob/master/src/views/AnnotationQueryEditor.tsx#L55). 

My question is whether there is a reason for this limitation, or if it's possible to just add tags to the list of query types for annotation. 

Thanks

**Comment by kminehart** [comment]
Nope it's totally possible! I must have just overlooked this. I'd welcome a pull request that included this change

**Comment by nazzzzz** [comment]
@kminehart Opened a small PR here: https://github.com/grafana/github-datasource/pull/96.
